//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_LOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUDIT_LOG()
        {
            this.AUDIT_LOG_DETAIL = new HashSet<AUDIT_LOG_DETAIL>();
        }
    
        public decimal AUDIT_LOG_ID { get; set; }
        public string USERID { get; set; }
        public string ACTION { get; set; }
        public System.DateTime CREATE_DTM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDIT_LOG_DETAIL> AUDIT_LOG_DETAIL { get; set; }
    }
}
