//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_LOG_DETAIL
    {
        public decimal AUDIT_DETAIL_ID { get; set; }
        public decimal AUDIT_LOG_ID { get; set; }
        public string TYPE { get; set; }
        public string VALUE { get; set; }
        public System.DateTime CREATE_DTM { get; set; }
    
        public virtual AUDIT_LOG AUDIT_LOG { get; set; }
    }
}
