//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_AUDIT_LOG
    {
        public decimal TAB_AUDIT_LOG_ID { get; set; }
        public string USERID { get; set; }
        public string TAB_NM { get; set; }
        public System.DateTime CREATE_DTM { get; set; }
    }
}
